# Developer: https://t.me/IBoTuS

# Placeholder %ibfish_<тип бочки,например legendary>% - Плейсхолдер для отображения игрока который словил наибольшее количество бочек данного типа
# Placeholder %ibfish_event% - Плейсхолдер для отображения времени до следующего ивента

settings: # Основные настройки
  world: # Разрешить в каких мирах можно словить бочку с предметами внутри
    - spawn
  replace-placeholder:
    no-player: "Нету" # Если никто еще не словил бочку
    event-active: "#0EC8E2Уже активный" # Если ивент активный
  event-time: 300 # Раз в сколько минут, должен произойти ивент
  bossbar: # Настройки боссбара
    enabled: true # Включить/Выключить боссбар
    time: 60 # Сколько будет длится ивент в секундах
    message: "#0EC8E2🔥 &fРыболовная лихорадка - #0EC8E2/spawn"
    color: BLUE # Цвет
    style: SOLID # Стиль

sound: # Настройки звука
  event-start: # Звук при запуске ивента
    sound: BLOCK_BEACON_POWER_SELECT
    volume: 1.0 # Громкость
    pitch: 1.0 # Темп

fishing: # Можно создать неограниченно количество бочок, например magical, legendary, epic и тд
  magical: # Тип бочки
    name: "#0EC8E2Магическая Бочка" # Имя бочки
    chance: 50 # Шанс
    glow: true # Подсветка бочки
    sound: ENTITY_PLAYER_LEVELUP # Звук при ловле бочки
    commands: # Команды при вылове бочки, чтобы отключить поставьте []
      - 'give %player% diamond 32'
  legendary:
    name: "#0EC8E2Легендарная Бочка"
    chance: 20
    glow: true
    sound: ENTITY_PLAYER_LEVELUP
    commands: []

messages:
  command: "#0EC8E2[✘] &7| &fБочка с именем #0EC8E2{name} &fне найдена в конфигурации."
  permission: "#0EC8E2[✘] &7| &fУ вас нет разрешения на выполнение этой команды."
  event-start: "#0EC8E2[✔] &7| &fИвент был запущен."
  event-running: "#0EC8E2[✔] &7| &fИвент уже запущен."
  reload: "#0EC8E2[✔] &7| &fКонфигурация успешно перезагружена."
  fishing: "#0EC8E2[✔] &7| &fПоздравляем, вы словили {barrel}"
  chance-loot: "#0EC8E2[✔] &7| &fШансы лута были сохранены!"
  save-loot: "#0EC8E2[✔] &7| &fЛут в бочке был сохранен!"